version: "3.8"
services:
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: skillsight_data
        ports:
            - "3306:3306"
        volumes:
            - ./DB_Script:/docker-entrypoint-initdb.d

    backend:
        build:
            context: .
            dockerfile: SkillSight_API/Dockerfile
        environment:
            - ConnectionStrings__DefaultConnection=Server=db;Port=3306;Database=skillsight_data;User=root;Password=password;
        depends_on:
            - db
        ports:
            - "5000:80"

    frontend:
        build:
            context: .
            dockerfile: SkillSight_Frontend/Dockerfile
        ports:
            - "4200:4200"
